# Loading Dataset

In [1]:
import pandas as pd

# Creating dataframe cs
cs = pd.read_excel("telco_dataset.xlsx", sheet_name = "main")

# Exploring Dataframe Dimension

In [ ]:
# Exploring the dimension of dataframe cs
cs.shape

(2120, 15)

In [ ]:
# Exploring the dimension of dataframe cs
# Notable column with empty values is column end_date
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   circuit_id              2120 non-null   object
 1   monthly_recurring_cost  2120 non-null   int64
 2   a_end                   2120 non-null   object
 3   z_end                   2120 non-null   object
 4   product_type            2120 non-null   object
 5   supplier                2120 non-null   object
 6   start_date              2120 non-null   object
 7   end_date                1598 non-null   object
 8   contract_term_months    2120 non-null   int64
 9   billing_status          2120 non-null   object
 10  decom_status            2120 non-null   object
 11  service_status          2120 non-null   object
 12  reclaim                 20 non-null     object
 13  reclaim_total           20 non-null     float64
 14  utilization_pct         2120 non-null   int64
dtypes: float64(1), int64(3), object(11)
memory usage: 248.6+ KB

In [ ]:
# Exploring values in dataframe cs
cs.head()

,circuit_id,monthly_recurring_cost,a_end,z_end,product_type,supplier,start_date,end_date,contract_term_months,billing_status,decom_status,service_status,reclaim,reclaim_total,utilization_pct
0,CKT-07237,2824,Dallas DC1,London DC2,Internet DIA,Orange,13-11-22,12-11-27,36,BILLING,PENDING DECOM,Provisioning,NaN,NaN,34
1,CKT-07085,350,Frankfurt DC1,Zurich DC1,Fiber,BT,2020-01-18,16-01-25,24,Not Billed,DECOM,Provisioning,NaN,NaN,75
2,CKT-02822,1316,London DC1,Tokyo DC1,Wave,Orange,2021/11/16,2024-11-15,36,billing,DECOM,Active,NaN,NaN,55
3,CKT-07997,4564,Zurich DC1,Amsterdam DC1,Metro Fiber,BT,28-01-21,NaN,36,BILLING,ACTIVE,Pending Disconnect,NaN,NaN,94
4,CKT-03339,150,Tokyo DC1,London DC1,Cross Connect,Lumen,2021/09/24,23-09-26,60,BILLING,PENDING DECOM,Provisioning,NaN,NaN,61

# Format Checking and Standardization

In [ ]:
# Format checking: a_end
sorted(cs['a_end'].unique())

['Amsterdam DC1',
 'Ashburn DC1',
 'Dallas DC1',
 'Frankfurt DC1',
 'Frankfurt DC2',
 'London DC1',
 'London DC2',
 'New York DC1',
 'Paris DC1',
 'Singapore DC1',
 'Sydney DC1',
 'Tokyo DC1',
 'Zurich DC1']

In [ ]:
# Format checking: z_end
sorted(cs['z_end'].unique())

['Amsterdam DC1',
 'Ashburn DC1',
 'Dallas DC1',
 'Frankfurt DC1',
 'Frankfurt DC2',
 'London DC1',
 'London DC2',
 'New York DC1',
 'Paris DC1',
 'Singapore DC1',
 'Sydney DC1',
 'Tokyo DC1',
 'Zurich DC1']

In [ ]:
# Format checking: product_type
sorted(cs['product_type'].unique())

['Cross Connect', 'Dark Fiber', 'Fiber', 'Internet DIA', 'Metro Fiber', 'Wave']

In [ ]:
# Format checking: supplier
sorted(cs['supplier'].unique())

['AT&T',
 'BT',
 'Colt',
 'Equinix',
 'Lumen',
 'NTT',
 'Orange',
 'Telstra',
 'Verizon',
 'Zayo']

In [ ]:
# Format checking: decom_status
sorted(cs.decom_status.unique())

['ACTIVE', 'DECOM', 'PENDING DECOM', 'TERMINATION REQUESTED']

In [ ]:
# Format checking: billing_status
sorted(cs['billing_status'].unique())

['ACTIVE BILLING', 'BILLING', 'Not Billed', 'billing']

In [2]:
# Standardizing format: billing_status

standardized = []

for c in cs['billing_status']:
    if "billing" in c.lower():
        standardized.append("BILLING")
    else:
        standardized.append("NOT BILLED")

cs['clean_billing_status'] = standardized

cs.head()

,circuit_id,monthly_recurring_cost,a_end,z_end,product_type,supplier,start_date,end_date,contract_term_months,billing_status,decom_status,service_status,reclaim,reclaim_total,utilization_pct,clean_billing_status
0,CKT-07237,2824,Dallas DC1,London DC2,Internet DIA,Orange,13-11-22,12-11-27,36,BILLING,PENDING DECOM,Provisioning,NaN,NaN,34,BILLING
1,CKT-07085,350,Frankfurt DC1,Zurich DC1,Fiber,BT,2020-01-18,16-01-25,24,Not Billed,DECOM,Provisioning,NaN,NaN,75,NOT BILLED
2,CKT-02822,1316,London DC1,Tokyo DC1,Wave,Orange,2021/11/16,2024-11-15,36,billing,DECOM,Active,NaN,NaN,55,BILLING
3,CKT-07997,4564,Zurich DC1,Amsterdam DC1,Metro Fiber,BT,28-01-21,NaN,36,BILLING,ACTIVE,Pending Disconnect,NaN,NaN,94,BILLING
4,CKT-03339,150,Tokyo DC1,London DC1,Cross Connect,Lumen,2021/09/24,23-09-26,60,BILLING,PENDING DECOM,Provisioning,NaN,NaN,61,BILLING

In [3]:
# Removing the column billing_status as it is replaced by column clean_billing_status
cs.drop(columns="billing_status", inplace=True)
cs.head()

,circuit_id,monthly_recurring_cost,a_end,z_end,product_type,supplier,start_date,end_date,contract_term_months,decom_status,service_status,reclaim,reclaim_total,utilization_pct,clean_billing_status
0,CKT-07237,2824,Dallas DC1,London DC2,Internet DIA,Orange,13-11-22,12-11-27,36,PENDING DECOM,Provisioning,NaN,NaN,34,BILLING
1,CKT-07085,350,Frankfurt DC1,Zurich DC1,Fiber,BT,2020-01-18,16-01-25,24,DECOM,Provisioning,NaN,NaN,75,NOT BILLED
2,CKT-02822,1316,London DC1,Tokyo DC1,Wave,Orange,2021/11/16,2024-11-15,36,DECOM,Active,NaN,NaN,55,BILLING
3,CKT-07997,4564,Zurich DC1,Amsterdam DC1,Metro Fiber,BT,28-01-21,NaN,36,ACTIVE,Pending Disconnect,NaN,NaN,94,BILLING
4,CKT-03339,150,Tokyo DC1,London DC1,Cross Connect,Lumen,2021/09/24,23-09-26,60,PENDING DECOM,Provisioning,NaN,NaN,61,BILLING

In [18]:
# Showing reclaim rows
reclaim_columns = ['circuit_id','monthly_recurring_cost','decom_status', 'service_status','clean_billing_status']
reclaim_condition = cs['reclaim'] == 'YES'

reclaim_df = cs.loc[reclaim_condition, reclaim_columns]

reclaim_df.head()

,circuit_id,monthly_recurring_cost,decom_status,service_status,clean_billing_status
44,CKT-00705,2565,DECOM,INACTIVE,BILLING
84,CKT-09044,300,DECOM,INACTIVE,BILLING
194,CKT-07283,3658,DECOM,INACTIVE,BILLING
314,CKT-08592,390,DECOM,INACTIVE,BILLING
327,CKT-08965,5000,DECOM,INACTIVE,BILLING

In [19]:
reclaim_df.to_excel('reclaim.xlsx', index = False)

In [ ]:
# Format checking: service_status
sorted(cs.service_status.unique())

['Active',
 'Inactive',
 'Pending Disconnect',
 'Provisioning',
 'Suspended',
 'active']

In [5]:
# Standardizing format: service_status
cs['service_status'] = cs.service_status.str.upper()
sorted(cs.service_status.unique())

['ACTIVE', 'INACTIVE', 'PENDING DISCONNECT', 'PROVISIONING', 'SUSPENDED']

In [6]:
# Standardizing format: start_date and end_date

cs['start_date'] = pd.to_datetime(cs['start_date'])
cs['end_date'] = pd.to_datetime(cs['end_date'])

cs[['start_date', 'end_date']].head()

/tmp/ipykernel_13746/3929806125.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cs['start_date'] = pd.to_datetime(cs['start_date'])
/tmp/ipykernel_13746/3929806125.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cs['end_date'] = pd.to_datetime(cs['end_date'])

  start_date   end_date
0 2022-11-13 2027-12-11
1 2020-01-18 2025-01-16
2 2021-11-16 2024-11-15
3 2021-01-28        NaT
4 2021-09-24 2026-09-23

In [7]:
# fill in missing end_date
blank_end_date = cs['end_date'].isna()

cs.loc[blank_end_date, 'end_date'] = cs.loc[blank_end_date].apply(
    lambda x: x['start_date'] + pd.DateOffset(months=x['contract_term_months']),
    axis=1
)

cs['end_date'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
2115    False
2116    False
2117    False
2118    False
2119    False
Name: end_date, Length: 2120, dtype: bool

In [8]:
min_date = cs['start_date'].min()
min_date

Timestamp('2017-01-01 00:00:00')

In [ ]:
max_date = cs['end_date'].max()
max_date

Timestamp('2028-11-03 00:00:00')

In [ ]:
# checking for rows with empty end_date

cs[cs['end_date'].isna()]

Empty DataFrame
Columns: [circuit_id, monthly_recurring_cost, a_end, z_end, product_type, supplier, start_date, end_date, contract_term_months, decom_status, service_status, reclaim, reclaim_total, utilization_pct, clean_billing_status]
Index: []

# Cost-Saving Analysis

In [20]:
# Cost-saving Objective I
# cost savings: decom_status = ACTIVE, billing_status = BILLING, service_status = INACTIVE

cs[(cs['service_status'] == 'INACTIVE') &
    (cs['decom_status'] == 'ACTIVE') &
     (cs['clean_billing_status'] == 'BILLING')].head()

,circuit_id,monthly_recurring_cost,a_end,z_end,product_type,supplier,start_date,end_date,contract_term_months,decom_status,service_status,reclaim,reclaim_total,utilization_pct,clean_billing_status,cost_saving,duplicate_route_flag,underused
21,CKT-04700,300,Dallas DC1,Amsterdam DC1,Fiber,BT,2017-05-23,2021-05-23,48,ACTIVE,INACTIVE,NaN,NaN,22,BILLING,YES,False,NO
32,CKT-08849,300,Amsterdam DC1,Zurich DC1,Dark Fiber,NTT,2018-03-19,2020-03-18,36,ACTIVE,INACTIVE,NaN,NaN,71,BILLING,YES,False,NO
35,CKT-02796,4974,London DC2,New York DC1,Wave,Zayo,2021-07-18,2024-07-17,36,ACTIVE,INACTIVE,NaN,NaN,34,BILLING,YES,False,NO
53,CKT-00446,350,Frankfurt DC1,New York DC1,Cross Connect,Zayo,2017-10-25,2022-10-25,60,ACTIVE,INACTIVE,NaN,NaN,36,BILLING,YES,False,NO
60,CKT-01646,4987,Tokyo DC1,Singapore DC1,Wave,AT&T,2018-02-22,2021-02-21,60,ACTIVE,INACTIVE,NaN,NaN,23,BILLING,YES,False,NO

In [21]:
# Cost-saving Objective I
# Flagging rows that are cost savings (decom_status = ACTIVE, billing_status = BILLING, service_status = INACTIVE)

cs['cost_saving'] = (
    (cs['decom_status'] == 'ACTIVE') &
    (cs['clean_billing_status'] == 'BILLING') &
    (cs['service_status'] == 'INACTIVE')
).map({True: 'YES', False: 'NO'})

cs[cs['cost_saving'] == 'YES'].head()

,circuit_id,monthly_recurring_cost,a_end,z_end,product_type,supplier,start_date,end_date,contract_term_months,decom_status,service_status,reclaim,reclaim_total,utilization_pct,clean_billing_status,cost_saving,duplicate_route_flag,underused
21,CKT-04700,300,Dallas DC1,Amsterdam DC1,Fiber,BT,2017-05-23,2021-05-23,48,ACTIVE,INACTIVE,NaN,NaN,22,BILLING,YES,False,NO
32,CKT-08849,300,Amsterdam DC1,Zurich DC1,Dark Fiber,NTT,2018-03-19,2020-03-18,36,ACTIVE,INACTIVE,NaN,NaN,71,BILLING,YES,False,NO
35,CKT-02796,4974,London DC2,New York DC1,Wave,Zayo,2021-07-18,2024-07-17,36,ACTIVE,INACTIVE,NaN,NaN,34,BILLING,YES,False,NO
53,CKT-00446,350,Frankfurt DC1,New York DC1,Cross Connect,Zayo,2017-10-25,2022-10-25,60,ACTIVE,INACTIVE,NaN,NaN,36,BILLING,YES,False,NO
60,CKT-01646,4987,Tokyo DC1,Singapore DC1,Wave,AT&T,2018-02-22,2021-02-21,60,ACTIVE,INACTIVE,NaN,NaN,23,BILLING,YES,False,NO

In [16]:
# savings file
cost_savings = cs[cs['cost_saving'] == 'YES']
cost_savings.to_excel('cost_savings.xlsx', index = False)

In [11]:
# Cost-saving Objective II: identify circuits that are potentially duplicate routes (the same product type, and A and Z locations).
# decom_status = ACTIVE, clean_billing_status = BILLING, service_status = ACTIVE and PROVISIONING)


# Create condition for the filter
cond = (
    (cs['decom_status'] == 'ACTIVE') &
    (cs['clean_billing_status'] == 'BILLING') &
    (cs['service_status'].isin(['ACTIVE', 'PROVISIONING']))
)

# Initialize column
cs['duplicate_route_flag'] = False

# Apply duplicate detection only on filtered rows
cs.loc[cond, 'duplicate_route_flag'] = cs.loc[cond].duplicated(
    ['a_end', 'z_end', 'product_type'], keep=False
)

# Get duplicate rows
duplicate_rows = cs[cs['duplicate_route_flag']] \
    .sort_values(['a_end', 'z_end', 'product_type'])

duplicate_rows[['circuit_id','a_end','z_end','product_type','duplicate_route_flag']].head()

,circuit_id,a_end,z_end,product_type,duplicate_route_flag
545,CKT-07155,Amsterdam DC1,Frankfurt DC1,Internet DIA,True
1450,CKT-01831,Amsterdam DC1,Frankfurt DC1,Internet DIA,True
1495,CKT-02331,Amsterdam DC1,Frankfurt DC1,Internet DIA,True
1520,CKT-07093,Amsterdam DC1,Frankfurt DC1,Internet DIA,True
788,CKT-00486,Ashburn DC1,Singapore DC1,Cross Connect,True

In [ ]:
# duplicate route file

duplicate_route = duplicate_rows.to_excel('duplicate_route.xlsx', index = False)

In [12]:
# Cost-saving Objective III: identify circuits that are underused (utilization percentage < 20%).
# Flagging underused circuits = < 20% utilization rate

cs['underused'] = (cs['utilization_pct'] < 20).map({True: 'YES', False: 'NO'})

cs[cs['underused'] == 'YES'].head()

,circuit_id,monthly_recurring_cost,a_end,z_end,product_type,supplier,start_date,end_date,contract_term_months,decom_status,service_status,reclaim,reclaim_total,utilization_pct,clean_billing_status,cost_saving,duplicate_route_flag,underused
6,CKT-01735,350,Frankfurt DC1,New York DC1,Cross Connect,Lumen,2022-07-05,2025-04-07,24,TERMINATION REQUESTED,PENDING DISCONNECT,NaN,NaN,13,NOT BILLED,NO,False,YES
9,CKT-02102,300,Ashburn DC1,Ashburn DC1,Dark Fiber,Equinix,2021-09-21,2026-09-20,48,TERMINATION REQUESTED,ACTIVE,NaN,NaN,5,BILLING,NO,False,YES
10,CKT-03037,4767,Amsterdam DC1,London DC1,Wave,Equinix,2022-09-25,2024-09-24,48,ACTIVE,ACTIVE,NaN,NaN,0,BILLING,NO,False,YES
12,CKT-09321,4340,Zurich DC1,Frankfurt DC2,Internet DIA,Lumen,2019-02-09,2022-02-08,60,ACTIVE,ACTIVE,NaN,NaN,8,BILLING,NO,False,YES
18,CKT-00754,150,Singapore DC1,Singapore DC1,Fiber,Telstra,2023-03-14,2025-03-13,60,DECOM,INACTIVE,NaN,NaN,11,NOT BILLED,NO,False,YES

In [ ]:
# Under_utilized file download

under_utilized = cs[cs['underused'] == 'YES']
under_utilized.to_excel('under_utilized.xlsx', index = False)

In [13]:
# Cost-saving Objective IV: identify out of term contracts but are still being billed to reassess usability.
cs[['circuit_id','start_date','end_date','contract_term_months']].head()

  circuit_id start_date   end_date  contract_term_months
0  CKT-07237 2022-11-13 2027-12-11                    36
1  CKT-07085 2020-01-18 2025-01-16                    24
2  CKT-02822 2021-11-16 2024-11-15                    36
3  CKT-07997 2021-01-28 2024-01-28                    36
4  CKT-03339 2021-09-24 2026-09-23                    60

In [14]:
# Exploring values in dataframe cs
cs[['circuit_id', 'start_date','end_date','contract_term_months']].head(1)

  circuit_id start_date   end_date  contract_term_months
0  CKT-07237 2022-11-13 2027-12-11                    36

Upon further investigation, inconsistencies are detected in the end_date and contract_term_months columns.

As an example, circuit CKT-07237 start date was on 2022-11-13, with a 36 contract term in months. Its contract should have ended on 2025-11-13, but it shows 2027-12-11 instead.

**`Further investigation on contract terms is highly recommended.`**